// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBYCP1ABgSplJtB3GdpuVsT0KxJytJDkgc',
    appId: '1:881951524233:web:430fdc797a34b7573b0d58',
    messagingSenderId: '881951524233',
    projectId: 'rosadamascena-331a6',
    authDomain: 'rosadamascena-331a6.firebaseapp.com',
    storageBucket: 'rosadamascena-331a6.appspot.com',
    measurementId: 'G-LNXGJDT4HH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA43zqAm4mo1v5issnmsuHjINHZYciZ7sY',
    appId: '1:881951524233:android:e2db1695201fbbd83b0d58',
    messagingSenderId: '881951524233',
    projectId: 'rosadamascena-331a6',
    storageBucket: 'rosadamascena-331a6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBwrEbcWvEDq0nkuJ2YTYZJkP2iP1trOP0',
    appId: '1:881951524233:ios:2fac9bc511fc2a903b0d58',
    messagingSenderId: '881951524233',
    projectId: 'rosadamascena-331a6',
    storageBucket: 'rosadamascena-331a6.appspot.com',
    iosBundleId: 'com.example.predictingRoseDiseases',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBwrEbcWvEDq0nkuJ2YTYZJkP2iP1trOP0',
    appId: '1:881951524233:ios:c3fbfecdf9ea00db3b0d58',
    messagingSenderId: '881951524233',
    projectId: 'rosadamascena-331a6',
    storageBucket: 'rosadamascena-331a6.appspot.com',
    iosBundleId: 'com.example.predictingRoseDiseases.RunnerTests',
  );
}
